apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoiYnVnYWV2YW1nLW1na29yb2x5IiwicGFzc3dvcmQiOiJnaHBfc3NRYjRjS2s5cEd6UHdFM3B4ZU41ZFVjWmhQRlpDMTVLaHNlIiwiZW1haWwiOiJidWdhZXZhbWdAZ21haWwuY29tIiwiYXV0aCI6IlluVm5ZV1YyWVcxbkxXMW5hMjl5YjJ4NU9tZG9jRjl6YzFGaU5HTkxhemx3UjNwUWQwVXpjSGhsVGpWa1ZXTmFhRkJHV2tNeE5VdG9jMlU9In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2026-02-04T16:00:59Z"
  name: dockerconfigjson
  namespace: cinemaabyss
  resourceVersion: "102607"
  uid: 8351e88a-a141-423a-89c6-00f8589a558e
type: kubernetes.io/dockerconfigjson
