# Образ контейнера
image:
  repository: ghcr.io/bugaevamg-mgkoroly/cinemaabyss_sprint2/proxy-service
  tag: main
  pullPolicy: IfNotPresent

# Порты
service:
  port: 8000

# Переменные окружения
env:
  MOVIES_MIGRATION_PERCENT: "50"
  GRADUAL_MIGRATION: "true"
  MONOLITH_URL: http://monolith-svc:8080
  MOVIES_SERVICE_URL: http://movies-svc:8081
  EVENTS_SERVICE_URL: http://event-service-svc:80

# Реплики
replicaCount: 2

# Ресурсы
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

# Ingress
ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: cinemaabyss.example.com
      paths:
        - path: /api/movies
          pathType: Prefix
        - path: /api/events
          pathType: Prefix
  tls: []
