apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJkb2NrZXIucGtnLmdpdGh1Yi5jb20iOiB7CiAgICAgICJhdXRoIjogIlZWTkZVazVCVFVVNloyaDFYMlZSUnpocFRsRkpaVWRuVjFVNGJHTnZaRUpNUlhSSVRuSTJjSEZhYlRKWlVWTnFidz09IgogICAgfSwKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJZblZuWVdWMllXMW5MVzFuYTI5eWIyeDVPbWRvZFY5bFVVYzRhVTVSU1dWSFoxZFZPR3hqYjJSQ1RFVjBTRTV5Tm5CeFdtMHlXVkZUYW04PSIKICAgIH0sCiAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewogICAgICAiYXV0aCI6ICJZMjlrWlhOd1lXTmxjMlJsZGpwa1pqQmxaVFpoWkMxbU9XSXlMVFF5TTJNdE9EYzRaaTAyTXpWa01HTTVOR1JqWXpJPSIKICAgIH0KICB9LAogICJIdHRwSGVhZGVycyI6IHsKICAgICJYLU1ldGEtU291cmNlLUNsaWVudCI6ICJnaXRodWIvY29kZXNwYWNlcyIKICB9Cn0=
type: kubernetes.io/dockerconfigjson
