apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: cinemaabyss
  labels:
    app: proxy-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      imagePullSecrets:
        - name: dockerconfigsecret
      containers:
      - name: proxy-service
        image: ghcr.io/bugaevamg-mgkoroly/cinemaabyss_sprint2/proxy-service:667b091b992fb996540a31d344b335268d150f73
        resources:  # <-- Добавляем эту секцию
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "300m"        
        ports:
        - containerPort: 8081
      
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  selector:
    app: proxy-service
  ports:
    - port: 8000
      targetPort: 8000