apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-service
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      imagePullSecrets:
        - name: dockerconfigsecret
      containers:
        - name: proxy-service
          image: ghcr.io/bugaevamg-mgkoroly/cinemaabyss_sprint2/proxy-service:e6e2ccbe4b89c4bfad1003aff5205f60223045e2
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: cinemaabyss-config
            - secretRef:
                name: cinemaabyss-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  selector:
    app: proxy-service
  ports:
    - port: 8000
      targetPort: 8000